### ISSUE TITLE
Numbers gwN

### ISSUE THREAD

**Issue by noskiddie** [Renater/SIPMediaGW#12]
Hi, I test your GW with Jitsi. Cant understand how manually add more gw containers to host and success rule traffik between them.

**Comment by nicotyze** [comment]
Hi, the maximum number of GWs you can launch on a machine is given by [CPU_PER_GW](https://github.com/Renater/SIPMediaGW/blob/599bf5e4365053e2d778e9bdb0d43eed2cd03da5/.env#L6) variable 
Each time you run SIPMediGW.sh, it will create an other gateway ( gw0, gw1,...), if you have CPU enough, on your machine.
Be aware that on a given machine you will be limited to a maximum of 8 gateways due to[ v4l2loopback](https://github.com/Renater/SIPMediaGW/blob/599bf5e4365053e2d778e9bdb0d43eed2cd03da5/test/provision.sh#L11C25-L11C37) limitations.

There is no direct traffic between the gateways: SIP signaling is coming through the SIP Server (kamailio) and media (audio/video) are relayed by the TURN server.
